import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // Provisioning Tokens (generated by IT admin, distributed to employees)
  provisioningTokens: defineTable({
    tokenHash: v.string(), // SHA-256 hash of the APT (e.g. "apt_live_xxx")
    employeeEmail: v.string(),
    department: v.string(),
    maxApps: v.number(), // How many apps this token can register (default 5)
    usedCount: v.number(),
    expiresAt: v.number(), // Token expiration timestamp
    isActive: v.boolean(),
    createdBy: v.string(), // Admin email who created the token
  })
    .index("by_token_hash", ["tokenHash"])
    .index("by_email", ["employeeEmail"]),

  // Registered agents (created on first provisioning)
  registeredAgents: defineTable({
    agentId: v.string(), // UUID generated at first provisioning
    employeeEmail: v.string(),
    department: v.string(),
    firstRegisteredAt: v.number(),
    lastSeenAt: v.number(),
    isActive: v.boolean(),
    revokedAt: v.optional(v.number()),
    revokedBy: v.optional(v.string()),
  })
    .index("by_agent_id", ["agentId"])
    .index("by_email", ["employeeEmail"]),

  // Per-app per-agent instances (one per app per agent)
  agentAppInstances: defineTable({
    agentId: v.string(),
    appName: v.string(),
    instanceTokenHash: v.string(), // SHA-256 hash of the instance token
    registeredAt: v.number(),
    expiresAt: v.number(),
    lastActivityAt: v.number(),
    monthlyRequests: v.number(), // Request counter for this app
  })
    .index("by_instance_token_hash", ["instanceTokenHash"])
    .index("by_agent_and_app", ["agentId", "appName"]),

  // Function Handle Registry: maps function aliases to actual function handles
  functionRegistry: defineTable({
    appName: v.string(),
    functionName: v.string(), // Alias e.g. "okr:getObjectives"
    functionHandle: v.string(), // Function handle string from createFunctionHandle()
    functionType: v.union(
      v.literal("query"),
      v.literal("mutation"),
      v.literal("action"),
    ),
    description: v.optional(v.string()),
    registeredAt: v.number(),
  }).index("by_app_and_function", ["appName", "functionName"]),

  // Dynamic permissions: who can do what on which app
  functionPermissions: defineTable({
    agentId: v.string(),
    appName: v.string(),
    functionPattern: v.string(), // e.g. "okr:*", "okr:createObjective", "*"
    permission: v.union(
      v.literal("allow"),
      v.literal("deny"),
      v.literal("rate_limited"),
    ),
    rateLimitConfig: v.optional(
      v.object({
        requestsPerHour: v.number(),
        tokenBudget: v.number(),
      }),
    ),
    createdAt: v.number(),
    createdBy: v.string(), // Admin email
  })
    .index("by_agent_and_app", ["agentId", "appName"])
    .index("by_app_and_pattern", ["appName", "functionPattern"]),

  // Audit log for all access attempts
  accessLog: defineTable({
    timestamp: v.number(),
    agentId: v.string(),
    appName: v.string(),
    functionCalled: v.string(),
    permission: v.string(), // "allow", "deny", "rate_limited"
    errorMessage: v.optional(v.string()),
    durationMs: v.optional(v.number()),
  })
    .index("by_agent_and_timestamp", ["agentId", "timestamp"])
    .index("by_app_and_function", ["appName", "functionCalled"]),

  // Component-level configuration (singleton "globals" table)
  componentConfig: defineTable({
    appName: v.string(),
    defaultPermissions: v.array(
      v.object({
        pattern: v.string(),
        permission: v.union(
          v.literal("allow"),
          v.literal("deny"),
          v.literal("rate_limited"),
        ),
        rateLimitConfig: v.optional(
          v.object({
            requestsPerHour: v.number(),
            tokenBudget: v.number(),
          }),
        ),
      }),
    ),
    configuredAt: v.number(),
  }),
});
